# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: adamnouri32706@gmail.com
author_name: adamnouri
contract_name: aidchain_contracts
deployment_language: python
preset_name: starter
project_name: aidchain-contracts

